module.exports = {
  	purge: {
		mode: 'layers',
		content: ['./public/**/*.html', './src/**/*.vue'],
	},
  	darkMode: false, // or 'media' or 'class'
  	theme: {
		screens: {
			'xs': '320px',
			// => @media (min-width: 640px) { ... }

			'sm': '640px',
			// => @media (min-width: 640px) { ... }

			'md': '768px',
			// => @media (min-width: 768px) { ... }

			'lg': '1024px',
			// => @media (min-width: 1024px) { ... }

			'xl': '1280px',
			// => @media (min-width: 1280px) { ... }

			'2xl': '1536px',
			// => @media (min-width: 1536px) { ... }
			
			// THIS BELOW USING MIN MAX
			// 'xs': {'min': '320px', 'max': '639px'},
			// 'sm': {'min': '640px', 'max': '767px'},
			// 'md': {'min': '768px', 'max': '1023px'},
			// 'lg': {'min': '1024px', 'max': '1279px'},
			// 'xl': {'min': '1280px', 'max': '1535px'},
			// '2xl': {'min': '1536px'},
		},
		minWidth: {
			'1/12': '6%',
			'1/8': '12%',
			'1/4': '25%',
			'1/2': '50%',
			'3/4': '75%',
			'full': '100%',
		},
    	extend: {
      		width: {
        		'28-persen': '28%',
				'30-persen': '30%'
      		}
    	},
  	},
  	variants: {
		accessibility: ['responsive', 'focus-within', 'focus'],
		alignContent: ['responsive', 'hover'],
		alignItems: ['responsive', 'hover'],
		alignSelf: ['responsive', 'hover'],
		animation: ['responsive', 'hover'],
		appearance: ['responsive', 'hover'],
		backgroundAttachment: ['responsive', 'hover'],
		backgroundClip: ['responsive', 'hover'],
		backgroundColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		backgroundImage: ['responsive', 'hover'],
		backgroundOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		backgroundPosition: ['responsive', 'hover'],
		backgroundRepeat: ['responsive', 'hover'],
		backgroundSize: ['responsive', 'hover'],
		borderCollapse: ['responsive', 'hover'],
		borderColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		borderOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		borderRadius: ['responsive', 'hover'],
		borderStyle: ['responsive', 'hover'],
		borderWidth: ['responsive', 'hover'],
		boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
		boxSizing: ['responsive', 'hover'],
		clear: ['responsive', 'hover'],
		container: ['responsive', 'hover'],
		cursor: ['responsive', 'hover'],
		display: ['responsive', 'hover'],
		divideColor: ['responsive', 'dark'],
		divideOpacity: ['responsive', 'dark'],
		divideStyle: ['responsive', 'hover'],
		divideWidth: ['responsive', 'hover'],
		fill: ['responsive', 'hover'],
		flex: ['responsive', 'hover'],
		flexDirection: ['responsive', 'hover'],
		flexGrow: ['responsive', 'hover'],
		flexShrink: ['responsive', 'hover'],
		flexWrap: ['responsive', 'hover'],
		float: ['responsive', 'hover'],
		fontFamily: ['responsive', 'hover'],
		fontSize: ['responsive', 'hover'],
		fontSmoothing: ['responsive', 'hover'],
		fontStyle: ['responsive', 'hover'],
		fontVariantNumeric: ['responsive', 'hover'],
		fontWeight: ['responsive', 'hover'],
		gap: ['responsive', 'hover'],
		gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
		gridAutoColumns: ['responsive', 'hover'],
		gridAutoFlow: ['responsive', 'hover'],
		gridAutoRows: ['responsive', 'hover'],
		gridColumn: ['responsive', 'hover'],
		gridColumnEnd: ['responsive', 'hover'],
		gridColumnStart: ['responsive', 'hover'],
		gridRow: ['responsive', 'hover'],
		gridRowEnd: ['responsive', 'hover'],
		gridRowStart: ['responsive', 'hover'],
		gridTemplateColumns: ['responsive', 'hover'],
		gridTemplateRows: ['responsive', 'hover'],
		height: ['responsive', 'hover'],
		inset: ['responsive', 'hover'],
		justifyContent: ['responsive', 'hover'],
		justifyItems: ['responsive', 'hover'],
		justifySelf: ['responsive', 'hover'],
		letterSpacing: ['responsive', 'hover'],
		lineHeight: ['responsive', 'hover'],
		listStylePosition: ['responsive', 'hover'],
		listStyleType: ['responsive', 'hover'],
		margin: ['responsive', 'hover'],
		maxHeight: ['responsive', 'hover'],
		maxWidth: ['responsive', 'hover'],
		minHeight: ['responsive', 'hover'],
		minWidth: ['responsive', 'hover'],
		objectFit: ['responsive', 'hover'],
		objectPosition: ['responsive', 'hover'],
		opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
		order: ['responsive', 'hover'],
		outline: ['responsive', 'focus-within', 'focus'],
		overflow: ['responsive', 'hover'],
		overscrollBehavior: ['responsive', 'hover'],
		padding: ['responsive', 'hover'],
		placeContent: ['responsive', 'hover'],
		placeItems: ['responsive', 'hover'],
		placeSelf: ['responsive', 'hover'],
		placeholderColor: ['responsive', 'dark', 'focus'],
		placeholderOpacity: ['responsive', 'dark', 'focus'],
		pointerEvents: ['responsive', 'hover'],
		position: ['responsive', 'hover'],
		resize: ['responsive', 'hover'],
		ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
		ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus'],
		ringOffsetWidth: ['responsive', 'focus-within', 'focus'],
		ringOpacity: ['responsive', 'dark', 'focus-within', 'focus'],
		ringWidth: ['responsive', 'focus-within', 'focus'],
		rotate: ['responsive', 'hover', 'focus'],
		scale: ['responsive', 'hover', 'focus'],
		skew: ['responsive', 'hover', 'focus'],
		space: ['responsive', 'hover'],
		stroke: ['responsive', 'hover'],
		strokeWidth: ['responsive', 'hover'],
		tableLayout: ['responsive', 'hover'],
		textAlign: ['responsive', 'hover'],
		textColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		textDecoration: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
		textOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
		textOverflow: ['responsive', 'hover'],
		textTransform: ['responsive', 'hover'],
		transform: ['responsive', 'hover'],
		transformOrigin: ['responsive', 'hover'],
		transitionDelay: ['responsive', 'hover'],
		transitionDuration: ['responsive', 'hover'],
		transitionProperty: ['responsive', 'hover'],
		transitionTimingFunction: ['responsive', 'hover'],
		translate: ['responsive', 'hover', 'focus'],
		userSelect: ['responsive', 'hover'],
		verticalAlign: ['responsive', 'hover'],
		visibility: ['responsive', 'hover'],
		whitespace: ['responsive', 'hover'],
		width: ['responsive', 'hover'],
		wordBreak: ['responsive', 'hover'],
		zIndex: ['responsive', 'focus-within', 'focus'],
    	extend: {
      		animation: ['hover', 'focus'],
    	},
  	},
  	plugins: [],
}
